### ISSUE TITLE
在平台调用设备功能如何在协议中进行处理（TCP直连）

### ISSUE THREAD

**Issue by EnthuDai** [jetlinks/demo-protocol#1]
demo有Write、Read、ReportPropertyMessage的处理样例，但是没有FunctionInvokeMessage的处理例子，FunctionInvokeMessage的处理与其他消息处理有较大区别，无法直接举一反三，望添加

**Comment by zhou-hao** [comment]
FunctionInvokeMessage 和 Read Write 流程应该是一样的哟

**Comment by EnthuDai** [comment]
> FunctionInvokeMessage 和 Read Write 流程应该是一样的哟

破案了，修改设备定义功能后没有点击 应用配置 按钮，导致系统没找到功能的定义。建议在修改设备保存后能提示是否应用配置，因为这个问题好几次出现问题了，汗
